version: "3.9"

services:
  postgres:
    image: 'postgres:13-alpine'
    # ports:
    #   - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - ./etl/.env

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  redis:
    image: 'redis:7'
    ports:
     - "6379:6379"

  etl:
    build: ./etl
    depends_on:
      - postgres
      - elastic
    env_file:
      - ./etl/.env
    volumes:
      - state_volume:/etl/state

  api:
    build:
      context: ./src
    env_file:
      - ./src/.env
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - elasticsearch

  # web:
  #   image: 'nginx:1.22'
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - api
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx/conf.d:/etc/nginx/conf.d

volumes:
  elasticsearch:
  state_volume:
  postgres:
